name: Minimal Working CI

on:
  push:
    branches: [ main ]

jobs:
  validate:
    name: Basic Validation
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Backend Check
      run: |
        cd backend
        npm install
        npm test
        
    - name: Frontend Check  
      run: |
        cd frontend
        npm install
        npm run build

    - name: Success
      run: echo "✅ Pipeline completed successfully!"