name: Working CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Backend
      working-directory: backend
      run: |
        npm install --legacy-peer-deps
        npm test

    - name: Frontend
      working-directory: frontend  
      run: |
        npm install --legacy-peer-deps
        npm run build

    - name: Complete
      run: echo "All tests and builds successful!"